/**
 * generated by Xtext
 */
package m.m;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Access</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m.m.Access#getNames <em>Names</em>}</li>
 * </ul>
 *
 * @see m.m.MPackage#getAccess()
 * @model
 * @generated
 */
public interface Access extends Expression
{
  /**
   * Returns the value of the '<em><b>Names</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Names</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Names</em>' attribute list.
   * @see m.m.MPackage#getAccess_Names()
   * @model unique="false"
   * @generated
   */
  EList<String> getNames();

} // Access
