/**
 * generated by Xtext
 */
package m.m;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Word</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m.m.Word#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see m.m.MPackage#getWord()
 * @model
 * @generated
 */
public interface Word extends Value
{
  /**
   * Returns the value of the '<em><b>Values</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Values</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' attribute list.
   * @see m.m.MPackage#getWord_Values()
   * @model unique="false"
   * @generated
   */
  EList<String> getValues();

} // Word
