/**
 * generated by Xtext
 */
package m.validation;

import m.validation.AbstractTextValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TextValidator extends AbstractTextValidator {
}
