#!/bin/sh
npx cspell --config Tooling/quality/cspell.json Documentation/**/*.md &&
npx markdownlint "Documentation/**/*.md" &&
find Documentation -exec npx write-good --no-illusion {} + &&
find Documentation -type f -exec npx markdown-link-check {} +