#!/bin/sh
npx cspell --config Tooling/quality/cspell.json Documentation/**/*.md &&
npx markdownlint Documentation/**/*.md &&
find Documentation -exec npx write-good {} + &&
find Documentation -exec npx markdown-link-check {} +