#!/bin/sh
npx cspell --config Tooling/quality/cspell.json Documentation/**/*.md &&
npx markdownlint Documentation/**/*.md &&
npx write-good --no-illusion Documentation/**/*.md &&
find Documentation -exec npx markdown-link-check {} +