/**
 * generated by Xtext
 */
package m.json;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m.json.BooleanValue#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see m.json.JsonPackage#getBooleanValue()
 * @model
 * @generated
 */
public interface BooleanValue extends Value
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * The literals are from the enumeration {@link m.json.Boolean}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see m.json.Boolean
   * @see #setValue(m.json.Boolean)
   * @see m.json.JsonPackage#getBooleanValue_Value()
   * @model
   * @generated
   */
  m.json.Boolean getValue();

  /**
   * Sets the value of the '{@link m.json.BooleanValue#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see m.json.Boolean
   * @see #getValue()
   * @generated
   */
  void setValue(m.json.Boolean value);

} // BooleanValue
