/**
 * generated by Xtext
 */
package m.json;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m.json.Object#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see m.json.JsonPackage#getObject()
 * @model
 * @generated
 */
public interface Object extends Value
{
  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link m.json.Field}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fields</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see m.json.JsonPackage#getObject_Fields()
   * @model containment="true"
   * @generated
   */
  EList<Field> getFields();

} // Object
