/*
 * generated by Xtext
 */
package m.ui;

import com.google.inject.Injector;
import m.ui.internal.MActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MActivator activator = MActivator.getInstance();
		return activator != null ? activator.getInjector(MActivator.M_M) : null;
	}

}
