/**
 * generated by Xtext
 */
package m.cs;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Access</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m.cs.Access#isNew <em>New</em>}</li>
 *   <li>{@link m.cs.Access#isRef <em>Ref</em>}</li>
 *   <li>{@link m.cs.Access#getPortions <em>Portions</em>}</li>
 * </ul>
 *
 * @see m.cs.CsPackage#getAccess()
 * @model
 * @generated
 */
public interface Access extends Expression
{
  /**
   * Returns the value of the '<em><b>New</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>New</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>New</em>' attribute.
   * @see #setNew(boolean)
   * @see m.cs.CsPackage#getAccess_New()
   * @model
   * @generated
   */
  boolean isNew();

  /**
   * Sets the value of the '{@link m.cs.Access#isNew <em>New</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>New</em>' attribute.
   * @see #isNew()
   * @generated
   */
  void setNew(boolean value);

  /**
   * Returns the value of the '<em><b>Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' attribute.
   * @see #setRef(boolean)
   * @see m.cs.CsPackage#getAccess_Ref()
   * @model
   * @generated
   */
  boolean isRef();

  /**
   * Sets the value of the '{@link m.cs.Access#isRef <em>Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' attribute.
   * @see #isRef()
   * @generated
   */
  void setRef(boolean value);

  /**
   * Returns the value of the '<em><b>Portions</b></em>' containment reference list.
   * The list contents are of type {@link m.cs.Portion}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Portions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Portions</em>' containment reference list.
   * @see m.cs.CsPackage#getAccess_Portions()
   * @model containment="true"
   * @generated
   */
  EList<Portion> getPortions();

} // Access
