/**
 * generated by Xtext
 */
package m.cs;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Else</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see m.cs.CsPackage#getElse()
 * @model
 * @generated
 */
public interface Else extends Block
{
} // Else
