/*
 * generated by Xtext
 */
package m


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MStandaloneSetup extends MStandaloneSetupGenerated {

	def static void doSetup() {
		new MStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
