grammar m.Testua with m.M

import "http://www.eclipse.org/emf/2002/Ecore" as ecore
import "http://www.minim.games/M"

@Override
Game:
	(entities+=Entity | systems+=System)*;

@Override
Loop:
	'entitate' entity=ID 'bakoitzarengatik' ('hurrengo' 'etiketekin' ':' constraints+=ID+)?
	'{' commands+=Command+ '}';

@Override
Branch:
	'baldin' 'eta' if=Condition
	('edo' elseIfs+=Condition)*
	('bestela' '{' commands+=Command+ '}')?;