/**
 * generated by Xtext
 */
package m.ide;

import m.ide.AbstractCSIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CSIdeModule extends AbstractCSIdeModule {
}
