/**
 * generated by Xtext 2.18.0
 */
package m.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import m.MRuntimeModule;
import m.MStandaloneSetup;
import m.ide.MIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MIdeSetup extends MStandaloneSetup {
  @Override
  public Injector createInjector() {
    MRuntimeModule _mRuntimeModule = new MRuntimeModule();
    MIdeModule _mIdeModule = new MIdeModule();
    return Guice.createInjector(Modules2.mixin(_mRuntimeModule, _mIdeModule));
  }
}
