/**
 * generated by Xtext
 */
package m.yaml;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m.yaml.File#getVersion <em>Version</em>}</li>
 *   <li>{@link m.yaml.File#getTags <em>Tags</em>}</li>
 *   <li>{@link m.yaml.File#getNodes <em>Nodes</em>}</li>
 * </ul>
 *
 * @see m.yaml.YamlPackage#getFile()
 * @model
 * @generated
 */
public interface File extends EObject
{
  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * The literals are from the enumeration {@link m.yaml.Version}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Version</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see m.yaml.Version
   * @see #setVersion(Version)
   * @see m.yaml.YamlPackage#getFile_Version()
   * @model
   * @generated
   */
  Version getVersion();

  /**
   * Sets the value of the '{@link m.yaml.File#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see m.yaml.Version
   * @see #getVersion()
   * @generated
   */
  void setVersion(Version value);

  /**
   * Returns the value of the '<em><b>Tags</b></em>' attribute list.
   * The list contents are of type {@link m.yaml.Tag}.
   * The literals are from the enumeration {@link m.yaml.Tag}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tags</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tags</em>' attribute list.
   * @see m.yaml.Tag
   * @see m.yaml.YamlPackage#getFile_Tags()
   * @model unique="false"
   * @generated
   */
  EList<Tag> getTags();

  /**
   * Returns the value of the '<em><b>Nodes</b></em>' containment reference list.
   * The list contents are of type {@link m.yaml.Node}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nodes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodes</em>' containment reference list.
   * @see m.yaml.YamlPackage#getFile_Nodes()
   * @model containment="true"
   * @generated
   */
  EList<Node> getNodes();

} // File
