/**
 * generated by Xtext
 */
package m.yaml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see m.yaml.YamlPackage#getNode()
 * @model
 * @generated
 */
public interface Node extends EObject
{
} // Node
