grammar m.Text with m.M

import "http://www.eclipse.org/emf/2002/Ecore" as ecore
import "http://www.minim.games/M"
import "http://www.minim.games/modular"
import "http://www.minim.games/expressions"

@Override
Module:
	(entities+=Entity|procedures+=Procedure)*
;

@Override
Loop:
	'bakoitza' identifier=IdentifierLiteral '!'
;

@Override
LogicalOr returns Expression:
	LogicalAnd ({LogicalOr.left=current} ('or'|'||'|'⋁') right=LogicalAnd)*;
