#!/usr/bin/python3

from subprocess import *

xtendFiles = 100
xtendLines = 10000
xtendBlanks = 1000
xtendComments = 0

def gradle():
    result = run(['gradle', 'shadowJar'])

    if result.returncode == 0:
        result = run(['gradle', 'clean'])
    return result.returncode

def scc():

    result = run(['scc', '..'], stdout=PIPE, stderr=PIPE)
    stdout = result.stdout.decode('utf-8')
    stderr = result.stderr.decode('utf-8')
    
    returncode = result.returncode

    for line in stdout.split('\n'):
        if (line.startswith('Xtend')):
            print (line)

            entries = []
            for entry in line.split(' '):
                if (entry != ''):
                    entries.append(entry)
            

            if int(entries[1]) > xtendFiles:
                print ("too many files")
                returncode = 1
            elif int(entries[2]) > xtendLines:
                print ("too many lines")
                returncode = 1
            elif int(entries[3]) > xtendBlanks:
                print ("too many blanks")
                returncode = 1
            elif int(entries[4]) > xtendComments:
                print ("too many comments")
                returncode = 1
    
    return returncode
        
returncode = scc() + gradle()
print ('Return code: %d' % returncode)
exit(returncode)