/**
 * generated by Xtext 2.18.0
 */
package m;

import m.TextStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TextStandaloneSetup extends TextStandaloneSetupGenerated {
  public static void doSetup() {
    new TextStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
