/*
 * generated by Xtext 2.18.0
 */
package m.ide

import com.google.inject.Guice
import m.MRuntimeModule
import m.MStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MIdeSetup extends MStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MRuntimeModule, new MIdeModule))
	}
	
}
