name: CI

on:
  pull_request:
    branches: 
      - master

jobs:
  lint:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository files
    - uses: actions/checkout@v1
    - name: Run pre-commit script
      run: |
        sh ./.github/pre-commit
