name: CI

on:
  [push, pull_request]

jobs:
  lint:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository files
      uses: actions/checkout@v1
    - name: Run linters
      run: |
        npm install &&
        npx cspell --config Tooling/quality/cspell.json Documentation/**/*.md &&
        npx markdownlint "Documentation/**/*.md" &&
        find Documentation -exec npx write-good --no-illusion {} + &&
        find Documentation -type f -exec npx markdown-link-check {} \;
