name: Integration

on:
  [push, pull_request]

jobs:
  lint:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository files
      uses: actions/checkout@v1
    - name: Cspell spell checker
      run: npx cspell --config .github/workflows/cspell.json **/*.md
    - name: Markdownlint-cli markdown structure
      run: npx markdownlint-cli -i LICENSE.md "**/*.md"
    - name: Write-good english linter
      run: |
        npx write-good --no-illusion README.md NOTICE.md
        find Documentation -exec npx write-good --no-illusion {} +
    - name: Download java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Download Checkstyle linting for java
      run: curl -L https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.27/checkstyle-8.27-all.jar -o check.jar
    - name: Run Checkstyle
      run: java -jar check.jar -c .github/workflows/checkstyle.xml Language\ server/src/ | grep WARN && exit 1 || exit 0
    - name: Compile java
      run: |
        cd Language\ server
        ./script.sh
