name: Integration

on:
  [push, pull_request]

jobs:
  lint:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository files
      uses: actions/checkout@v1
    - name: Install npm
      run: npm install
    - name: Cspell spell checker
      run: npx cspell --config Tooling/quality/cspell.json Documentation/**/*.md
    - name: Markdownlint markdown structure
      run: npx markdownlint "Documentation/**/*.md"
    - name: Write-good english linter
      run: find Documentation -exec npx write-good --no-illusion {} +
    - name: Markdown link check
      run: find Documentation -type f -exec npx markdown-link-check {} \;
    - name: Download java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile java
      run: |
        javac Core/m/source/main/Main.java &&
        java -cp "Core/m/source/" main.Main 