name: Integration

on:
  [push, pull_request]

jobs:
  lint:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository files
      uses: actions/checkout@v1
    - name: Cspell spell checker
      run: npx cspell --config .github/workflows/cspell.json **/*.md
    - name: Markdownlint-cli markdown structure
      run: npx markdownlint-cli -i LICENSE.md "**/*.md"
    - name: Write-good english linter
      run: |
        npx write-good --no-illusion README.md NOTICE.md
        find Documentation -exec npx write-good --no-illusion {} +
    - name: Markdown link check
      run: |
        npx markdown-link-check README.md
        npx markdown-link-check NOTICE.md
        find Documentation -type f -exec npx markdown-link-check {} \;
    - name: Download java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile java
      run: |
        cd Language\ Server
        ./script.sh
