name: Integration

on:
  [push, pull_request]

jobs:
  lint:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository files
      uses: actions/checkout@v1
    - name: Cspell spell checker
      run: npx cspell --config .github/workflows/configuration/cspell.json **/*.md
    - name: Markdownlint-cli markdown structure
      run: npx markdownlint-cli -i LICENSE.md "**/*.md"
    - name: Write-good english linter
      run: |
        npx write-good --no-illusion README.md NOTICE.md
        find Documentation -exec npx write-good --no-illusion {} +
    - name: Download java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Download Checkstyle linting for java
      run: curl -L https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.27/checkstyle-8.27-all.jar -o check.jar
    - name: Run Checkstyle
      run: java -jar check.jar -c .github/workflows/configuration/checkstyle.xml Language\ server/src/ | grep WARN && exit 1 || exit 0
    - name: Download dependency jars
      run: |
        cd Language\ server
        [ ! -d lib ] && mkdir lib
        [ ! -d lib/classes ] && mkdir lib/classes

        [ ! -f lib/classes/xtext.ide.jar ] && curl https://search.maven.org/remotecontent?filepath=org/eclipse/xtext/org.eclipse.xtext.ide/2.20.0/org.eclipse.xtext.ide-2.20.0.jar -o lib/classes/xtext.ide.jar
        [ ! -f lib/classes/guice.jar ] && curl https://search.maven.org/remotecontent?filepath=com/google/inject/guice/4.2.2/guice-4.2.2.jar -o lib/classes/guice.jar
    - name: Compile java project
      run: |
        cd Language\ server
        javac -d bin -cp src/:lib/classes/* src/m/main/*.java
    - name: Create jar from compiled classes
      run: |
        cd Language\ server/bin
        jar ecfv m.main.Main ../m.jar m/
    - name: Run jar file
      run: |
        cd Language\ server
        java -jar m.jar