name: Lint, Build and Test
on: [push, repository_dispatch]
defaults:
  run:
    shell: bash
jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v2
      - name: Markdown
        run: npx markdownlint-cli -i LICENSE.md "**/*.md"
        continue-on-error: true
      - name: Yaml
        run: find . -name "*.yaml" -exec npx yaml-lint {} +
        continue-on-error: true
      - name: Not linted
        run: find . -type f -not -wholename "./.git/*" -not -name "*.md" -not -name "*.yaml" -exec echo {} \;
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      languageServer: m.jar
      application: m.appImage
    steps:
      - name: Install java 11
        run: |
          sudo apt install openjdk-11-jdk
          sudo update-java-alternatives --set java-1.11.0-openjdk-amd64
      - name: Download repository
        uses: actions/checkout@v2
      - name: Run gradle
        run: gradle execute
      - name: Install node 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install yarn with node 10
        run: npm install -g yarn
      - name: Install electron-builder globally
        run: npm install -g electron-builder
      - name: Create Release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Tag ${{ github.ref }}
          release_name: Prerelease ${{ github.ref }}
          draft: true
          prerelease: true
      - name: Build theia
        working-directory: Code/Theia
        run: yarn update
      - name: Package the application
        working-directory: Code/Theia
        run: electron-builder .
      - name: Upload application to release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Code/Theia/dist/m-0.0.0.AppImage
          asset_name: m.AppImage