on: [push,repository_dispatch]
jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}    
    timeout-minutes: 1
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Hello
        run: echo Hello from ${{ matrix.os }}
      - name: Markdown
        run: |
          for x in *
          do
            echo $x
          done
