on: [push, repository_dispatch]
defaults:
  run:
    shell: bash
jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v2
      - name: Markdown
        run: npx markdownlint-cli -i LICENSE.md "**/*.md"
        continue-on-error: true
      - name: Yaml
        run: find . -name "*.yaml" -exec npx yaml-lint {} +
        continue-on-error: true
      - name: Not linted
        run: find . -type f -not -wholename "./.git/*" -not -name "*.md" -not -name "*.yaml" -exec echo {} \;
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      languageServer: m.jar
      application: m.appImage
    steps:
      - name: Download java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: java -version
      - name: Checkout repository files
        uses: actions/checkout@v2
      - name: Compile Xtend
        run: gradle generateXtext
      - name: Test
        run: |
          gradle --version
      - name: Run gradle
        run: gradle execute
