on: [push, repository_dispatch]
defaults:
  run:
    shell: bash
jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v2
      - name: Markdown
        run: npx markdownlint-cli -i LICENSE.md "**/*.md"
        continue-on-error: true
      - name: Yaml
        run: |
          sudo apt install yamllint
          yamllint .
        continue-on-error: true
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      languageServer: m.jar
      application: m.appImage
    steps:
      - name: Install java 11
        run: |
          sudo apt install openjdk-11-jdk
          sudo update-java-alternatives --set java-1.11.0-openjdk-amd64
      - name: Download repository
        uses: actions/checkout@v2
      - name: Create build.gradle
        run: >
          cat >build.gradle <<EOL

          plugins { id "org.xtext.xtend" version "2.0.8" }
          
          repositories.jcenter()
          
          dependencies { compile 'org.eclipse.xtend:org.eclipse.xtend.lib:2.21.0' }
          
          sourceSets { main.java.srcDirs = ['Code/m/src/m/build']}
          
          task execute (type: Exec) {
          
            dependsOn generateXtext
          
            commandLine "java", "-cp", project.configurations.compile.getAsPath(), "build/xtend/main/m/build/Main.java", "Code/m"
          
          }
          
          EOL
      - name: Run gradle
        run: gradle execute
      - name: Remove gradle file for sonar
        run: rm build.gradle
      - name: Create sonar configuration
        run: >
          cat >sonar-project.properties <<EOL

          sonar.organization=martin-azpillaga

          sonar.projectKey=martin-azpillaga_M

          sonar.sources=.
          
          sonar.java.binaries=Code/build/classes/java/main
          
          EOL
      - name: Sonarcloud after xtend
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Install node 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install yarn with node 10
        run: npm install -g yarn
      - name: Build theia
        working-directory: Code/Theia
        run: yarn update
