name: Publish

on:
  pull_request:
    types: [closed]

jobs:
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v1
      - name: Install ruby dev
        run: sudo apt install ruby-dev
      - name: Install twurl
        run: sudo gem install twurl
      - name: Create twurl configuration file
        env:
          consumer: ${{ secrets.TWITTER_CONSUMER_TOKEN }}
          consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: printf "profiles:\n\ \ AzpillagaWorld:\n\ \ \ \ $consumer:\n\ \ \ \ \ \ username:\ AzpillagaWorld\n\ \ \ \ \ \ consumer_key:\ $consumer\n\ \ \ \ \ \ consumer_secret:\ $consumer_secret\n\ \ \ \ \ \ token:\ $access\n\ \ \ \ \ \ secret:\ $access_secret\nconfiguration:\n\ \ default_profile:\n\ \ -\ AzpillagaWorld\n\ \ -\ $consumer" | sed "s/\\\/ /g" > ~/.twurlrc
      - name: Create Tweet
        run: twurl -d "status=$(git log -1 --pretty=format:"%s")" /1.1/statuses/update.json
