name: Publish

on: push

jobs:
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v1
      - name: Install ruby dev
        run: sudo apt install ruby-dev
      - name: Install twurl
        run: sudo gem install twurl
      - name: Copy twurlrc
        env: # Or as an environment variable
          super_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          echo $super_secret
          printf "profiles:\n\ \ AzpillagaWorld:\n\ \ \ \ ***REMOVED***:\n\ \ \ \ \ \ username:\ AzpillagaWorld\n\ \ \ \ \ \ consumer_key:\ ***REMOVED***\n\ \ \ \ \ \ consumer_secret:\ ***REMOVED***\n\ \ \ \ \ \ token:\ ***REMOVED***-9sEwF06Q5vjQe2DbfSNPTV9hctKK3l\n\ \ \ \ \ \ secret:\ $super_secret\nconfiguration:\n\ \ default_profile:\n\ \ -\ AzpillagaWorld\n\ \ -\ ***REMOVED***" | sed "s/\\\/ /g" > ~/.twurlrc
          cat ~/.twurlrc
      - name: Create Tweet
        run: twurl -d "status=$(git log -1 --pretty=format:"%s")" /1.1/statuses/update.json
