on: push
jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Versions
        run: |
          node --version
          yarn --version
          python --version
      - name: Download repository
        uses: actions/checkout@v2
      - name: Check other files
        run: |
          find . -type f \
          -not -wholename "*.git*" -and \
          -not -name "*.md" -and \
          -not -name "*.yaml" -and \
          -not -name "*.gradle" -and \
          -not -name "*.java" -and \
          -not -name "*.json" -and \
          -not -name "*.js" -and \
          -not -name "*.xtext" -and \
          -not -name "*.mwe2" \
          -not -name "*.lock" \
          | grep "." && exit 1 || exit 0
      - name: Install node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            checkstyle-8.34-all.jar
          key: format
      - name: Install node packages
        run: |
          npm install markdownlint-cli
          npm install npm-groovy-lint
          npm install jsonlint
          npm install js-beautify
          npm install yaml-lint
          [ -f checkstyle-8.34-all.jar ] || wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.34/checkstyle-8.34-all.jar
      - name: Lint Markdown
        run: |
          npx markdownlint-cli -i LICENSE.md -i node_modules "**/*.md"
      - name: Lint Yaml
        run: |
          find . -not -wholename "*node_modules*" -name "*.yaml" -exec sh -c 'npx yamllint {}' \;
      - name: Lint Groovy
        run: |
          npx npm-groovy-lint -i "**/node_modules/**/*"
      - name: Lint Json
        run: |
          find . -not -wholename "*node_modules*" -name "*.json" -not -name "*local-storage.json" -exec sh -c 'npx jsonlint {} > current && cmp current {}' \; | grep differ && exit 1 || exit 0
      - name: Lint Javascript
        run: |
          find . -not -wholename "*node_modules*" -name "*.js" -exec sh -c 'npx js-beautify {} > current && cmp current {}' \; | grep differ && exit 1 || exit 0
      - name: Lint java
        run: |
          java -jar checkstyle-8.34-all.jar -c /sun_checks.xml Code/Language/m/src || exit 0
  structure:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            node_modules
          key: structure
      - name: Install java 13
        uses: actions/setup-java@v1
        with:
          java-version: '13'
      - name: Install eslint
        run: |
          npm install eslint
      - name: Build language server
        working-directory: Code/Language
        run: |
          mkdir m.ide m.ui
          gradle shadowJar
      - name: Lint Java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export SONAR_SCANNER_VERSION=4.2.0.1873
          export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
          curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
          export PATH=$SONAR_SCANNER_HOME/bin:$PATH
          export SONAR_SCANNER_OPTS="-server"
          sonar-scanner \
          -Dsonar.organization=martin-azpillaga \
          -Dsonar.projectKey=martin-azpillaga_M \
          -Dsonar.sources=Code/Editor,Code/Language/m/src \
          -Dsonar.java.binaries=Code/Language/build/classes \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=c1285d7b6c459b50e7eee08102a94f4b68bd70f9
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - name: Install vuepress
        run: |
          sudo npm install -g vuepress
          cp -r Documentation ../Documentation
          git fetch
          git checkout gh-pages
          cp -r ../Documentation Documentation
          cd Documentation
          sudo vuepress build
          cd ..
          cp -r Documentation/.vuepress/dist/* .
          sudo rm -rf Documentation/
          git config --global user.name "Github actions"
          git config --global user.email "media@azpillaga.world"  
          git add .
          git commit -m "Deploy vuepress site using Github actions"
          git push
          git reset --hard
          git checkout -
      - name: Install java 13
        uses: actions/setup-java@v1
        with:
          java-version: '13'
      - name: Install python 2.7
        run: |
          sudo apt-get install python2.7
      - name: Install node 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install pandoc
        run: |
          sudo apt-get remove pandoc
          [ -f pandoc-2.9.1-1-amd64.deb ] || wget https://github.com/jgm/pandoc/releases/download/2.9.1/pandoc-2.9.1-1-amd64.deb
          sudo dpkg -i pandoc-2.9.1-1-amd64.deb
      - name: Install yarn and libx11
        run: |
          npm install -g yarn
          sudo apt-get install libx11-dev libxkbfile-dev
      - name: Build language server
        working-directory: Code/Language
        run: |
          mkdir m.ide m.ui
          gradle shadowJar
          cp build/libs/Language-ls-ls.jar ../Editor/ls.jar
      - name: Build documentation
        run: |
          find . -name "*.md" | sort | xargs -d "\n" pandoc > Code/Editor/Documentation.html
      - name: Build tests
        run: |
          pandoc README.md -t json | node Automation/reader.js > Code/Editor/test.js
          cp Automation/mobot.js Code/Editor/mobot.js
      - name: Upload Code/Editor folder to github artifacts
        uses: actions/upload-artifact@v2
        with:
          name: editor
          path: Code/Editor
  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - name: Download IDE folder
        uses: actions/download-artifact@v2
        with:
          name: editor
      - name: Install node 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install yarn and libx11
        run: |
          npm install -g yarn
          sudo apt install libx11-dev libxkbfile-dev
      - name: Build ide for browser
        run: |
          yarn
          yarn theia build
      - name: Run tests
        run: |
          mkdir workspace
          yarn theia start --app-target browser workspace &
          Xvfb :3 &
          sleep 5 && xvfb-run yarn mocha test.js
  packagingWindows:
    needs: test
    runs-on: windows-latest
    timeout-minutes: 100
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
      - name: Download Editor folder
        uses: actions/download-artifact@v2
        with:
          name: editor
      - name: Install node 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0
      - name: Build Editor for electron
        run: |
          npm config set python python2.7
          npm install -g yarn
          yarn
          yarn theia rebuild:electron
          yarn theia build --app-target electron
      - name: Package application
        run: |
          yarn electron-builder
      - name: Upload Exe
        if: ${{ matrix.os }} == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: "dist\\m 0.2.0.exe"
  packagingUbuntu:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - name: Download the editor folder
        uses: actions/download-artifact@v2
        with:
          name: editor
      - name: Install node 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install yarn
        run: |
          npm install -g yarn
          node --version
          yarn --version
          python --version
      - name: Build Editor for electron
        run: |
          yarn
          yarn theia rebuild:electron
          yarn theia build --app-target electron
      - name: Package application
        run: |
          yarn electron-builder
      - name: Upload AppImage
        if: ${{ matrix.os }} == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: dist/m-0.2.0.AppImage
  release:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [packagingUbuntu, packagingWindows]
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
      - name: Download Linux
        uses: actions/download-artifact@v2
        with:
          name: linux
      - name: Download Windows
        uses: actions/download-artifact@v2
        with:
          name: windows
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Tag ${{ github.ref }}
          release_name: Prerelease ${{ github.ref }}
          draft: true
          prerelease: true
      - name: Upload appimage to release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./m-0.2.0.AppImage
          asset_name: m.AppImage
          asset_content_type: text/text
      - name: Upload exe to release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./m 0.2.0.exe
          asset_name: m.exe
          asset_content_type: text/text
