name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
    - name: Install bats
      run: sudo apt install bats

    - name: Checkout repository files
      uses: actions/checkout@v1

    - name: Download java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Create jar
      run: |
        cd Code
        mkdir m.ide m.ui
        gradle jar

    - name: Create fat jar
      run: |
        cd Code
        gradle fatjar
