name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
    - name: Install bats
      run: sudo apt install bats

    - name: Checkout repository files
      uses: actions/checkout@v1

    - name: Download java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile java
      run: |
        cd Code
        javac -d bin -cp "." *.java

    - name: Create jar with compiled classes
      run: |
        cd Code/bin
        jar ecfv Main ../../Tests/ls.jar .
