<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="game" nsURI="azpillaga.world/game" nsPrefix="game">
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EReference" name="archetypes" upperBound="-1"
        eType="#//Archetype" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systems" upperBound="-1"
        eType="#//System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//End" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Archetype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="base" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Selection" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positiveStatements" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="negativeStatements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Iteration" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Forall" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atom" eType="#//Atom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Orable" abstract="true" interface="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Andable" abstract="true" interface="true"
      eSuperTypes="#//Orable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equatable" abstract="true" interface="true"
      eSuperTypes="#//Andable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comparable" abstract="true" interface="true"
      eSuperTypes="#//Equatable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Addable" abstract="true" interface="true"
      eSuperTypes="#//Comparable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multipliable" abstract="true" interface="true"
      eSuperTypes="#//Addable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Setable" abstract="true" interface="true"
      eSuperTypes="#//Multipliable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//Orable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Orable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Andable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Andable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Andable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Equatable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Equality" eSuperTypes="#//Equatable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//EqualityKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Equatable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Comparable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comparison" eSuperTypes="#//Comparable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ComparisonKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Comparable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Addable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Addition" eSuperTypes="#//Addable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//AdditiveKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Addable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Multipliable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplication" eSuperTypes="#//Multipliable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//MultiplicativeKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Multipliable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Setable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetExpression" eSuperTypes="#//Setable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//SetKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Setable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Primary"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Primary" abstract="true" interface="true"
      eSuperTypes="#//Setable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Primary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalNot" eSuperTypes="#//Primary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Cardinal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cardinal" eSuperTypes="#//Primary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Primary"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collection" abstract="true" interface="true"
      eSuperTypes="#//Primary"/>
  <eClassifiers xsi:type="ecore:EClass" name="Brackets" eSuperTypes="#//Collection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//Collection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicitSet" eSuperTypes="#//Collection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExplicitSet" eSuperTypes="#//Collection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" abstract="true" interface="true"
      eSuperTypes="#//Primary"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="component" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EqualityKind">
    <eLiterals name="equal" literal="="/>
    <eLiterals name="notEqual" value="1" literal="≠"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonKind">
    <eLiterals name="lower" literal="&lt;"/>
    <eLiterals name="lowerOrEqual" value="1" literal="≤"/>
    <eLiterals name="greaterOrEqual" value="2" literal="≥"/>
    <eLiterals name="greater" value="3" literal=">"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AdditiveKind">
    <eLiterals name="add" literal="+"/>
    <eLiterals name="subtract" value="1" literal="-"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MultiplicativeKind">
    <eLiterals name="multiply" literal="×"/>
    <eLiterals name="divide" value="1" literal="÷"/>
    <eLiterals name="remainder" value="2" literal="remainder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SetKind">
    <eLiterals name="membership" literal="∈"/>
    <eLiterals name="union" value="1" literal="∪"/>
    <eLiterals name="intersection" value="2" literal="∩"/>
    <eLiterals name="difference" value="3" literal="∖"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="End"/>
  <eClassifiers xsi:type="ecore:EClass" name="asdasdasdasdsa"/>
</ecore:EPackage>
